### PR TITLE
Add unit test example

### PR DESCRIPTION
**Pull request by e0ipso**
If I understand correctly using Plug would allow us to write proper unit tests.

Would it be possible to add an example?

### CODE REVIEW

**Comment by e0ipso** [comment]
Sure thing. There are many ways you can achieve this, I'll go for simple first. Other approaches are way more powerful but involve `xautoload` core's services.

**Comment by amitaibu** [comment]
> I'll go for simple first

Sounds like a good approach ! ;)

**Comment by e0ipso** [comment]
@amitaibu there you go.

It is **that** fast.
test result site-install 2015-01-27 11-11-45

@plopesc please review.

**Comment by amitaibu** [comment]
nice! :)

**Comment by plopesc** [comment]
This is pretty cool, man!

**Comment by e0ipso** [comment]
Merging after tests came back green.

**Pull request merged**
